### ISSUE TITLE
[bug] total_size will always be 0

### ISSUE THREAD

**Issue by fuomag9** [p0dalirius/streamableDownloader#1]
https://github.com/p0dalirius/streamableDownloader/blob/0450f57e40b6b775b7d74a8733da3625a81cf70a/streamableDownloader.py#L74 as the `if block` below:

```
            if 'Content-Length' in r.headers.keys():
                total_size = str(r.headers['Content-Length'])
```
will be ignored by the linked line statement

**Comment by p0dalirius** [comment]
Yes it's useless but does not have any impact.

Best regards,
